spring:
  application:
    name: mq-tutorials
  rabbitmq:
    username: buddy
    password: pass1234
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 5
        default-requeue-rejected: false

logging:
  level:
    org: ERROR